### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by VIcticious** [NillerMedDild/Enigmatica4#334] opened 2020-03-28 06:53 UTC
**Modpack version**
0.5.0

**Issue**
In crash report the game is crashing due to issues with rendering a Minecart? Also seperate issue, game wont load with 1.4.4 version of Optifine, Specificly version 1.4.4_HD_U_F5, if that helps or means anything.

**Logs**
Input pastebin link to crash-report or latest log, if applicable
[crash-2020-03-28_02.47.15-client.txt](https://github.com/NillerMedDild/Enigmatica4/files/4396739/crash-2020-03-28_02.47.15-client.txt)

**Comment by NielsPilgaard** [comment] 2020-03-28 09:35
Duplicate of #330

**Closed as completed by NielsPilgaard** 2020-03-28 09:35 UTC
Labels: Duplicate
