### ISSUE TITLE
Suggestion: Ender Tanks

### ISSUE THREAD

**Issue by douyabian** [NillerMedDild/Enigmatica4#259] opened 2020-01-13 06:49 UTC
https://www.curseforge.com/minecraft/mc-mods/endertanks

An alternative fluid tank with variable storage size, pump speed and dimensionality

**Comment by NielsPilgaard** [comment] 2020-01-13 07:38
Duplicate of #222 
It's still too buggy I'm afraid.

**Closed as completed by NielsPilgaard** 2020-01-13 07:38 UTC
Labels: Duplicate

**Comment by douyabian** [comment] 2020-01-13 09:42
Right, my bad, had a bad search and didn't see it! unfortunate that it's still buggy
